version: '3.9'
services:
  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"

  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  hotwired_ats:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
