default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  database: hotwired_ats_development

test:
  <<: *default
  database: hotwired_ats_test

production:
  <<: *default
  database: hotwired_ats_production
  username: hotwired_ats
  password: <%= ENV["HOTWIRED_ATS_DATABASE_PASSWORD"] %>
